blender_path = ""
ide_path = ""
current_settings_file = "C:\\Users\\Mythical\\Documents\\GitHub\\tempo_gui\\assets\\base\\presets\\default\\settings.json"
settings_files = ["C:\\Users\\Mythical\\Documents\\GitHub\\tempo_gui\\assets\\base\\presets\\default\\settings.json"]
app_x_position = 480.0
app_y_position = 240.0
app_width = 420.0
app_height = 600.0
